### ISSUE TITLE
Exporter hung but didn't exit

### ISSUE THREAD

**Issue by chibbert** [frankiexyz/ping-exporter#19]
I'm running the ping exporter as a systemd service as suggested in the readme.

I noticed in my grafana dashboard that the ping stats had stopped.

systemd status show the service is still running, but the last logs show an exception:

sudo systemctl status ping_exporter.service
● ping_exporter.service - Ping Exporter for Prometheus (Created By Frankie)
     Loaded: loaded (/etc/systemd/system/ping_exporter.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-06-06 22:33:36 BST; 1 weeks 6 days ago
   Main PID: 1112248 (python)
      Tasks: 1 (limit: 9239)
     Memory: 8.9M
     CGroup: /system.slice/ping_exporter.service
             └─1112248 /usr/bin/python /opt/ping-exporter.py

Jun 16 23:14:39 micro python[1112248]:     self.RequestHandlerClass(request, client_address, self)
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
Jun 16 23:14:39 micro python[1112248]:     self.finish()
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
Jun 16 23:14:39 micro python[1112248]:     self.wfile.close()
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Jun 16 23:14:39 micro python[1112248]:     self.flush()
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Jun 16 23:14:39 micro python[1112248]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Jun 16 23:14:39 micro python[1112248]: error: [Errno 32] Broken pipe
chibbert@micro:~$ sudo journalctl ping_exporter.service

journalctl logs suggest something went bad and never recovered:
Jun 16 23:14:34 micro python[1112248]: 127.0.0.1 - - [16/Jun/2021 23:14:34] "GET /probe?prot=4&target=www.google.co.uk HTTP/1.1" 200 -
Jun 16 23:14:34 micro python[1112248]: 2021-06-16 23:14:34,994 root         INFO     /usr/bin/fping -4 -b 56 -i 1 -p 500 -q -c 10 www.google.co.uk
Jun 16 23:14:39 micro python[1112248]: 127.0.0.1 - - [16/Jun/2021 23:14:39] "GET /probe?prot=4&target=www.google.co.uk HTTP/1.1" 200 -
Jun 16 23:14:39 micro python[1112248]: Traceback (most recent call last):
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
Jun 16 23:14:39 micro python[1112248]:     self.finish_request(request, client_address)
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
Jun 16 23:14:39 micro python[1112248]:     self.RequestHandlerClass(request, client_address, self)
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
Jun 16 23:14:39 micro python[1112248]:     self.finish()
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
Jun 16 23:14:39 micro python[1112248]:     self.wfile.close()
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Jun 16 23:14:39 micro python[1112248]:     self.flush()
Jun 16 23:14:39 micro python[1112248]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Jun 16 23:14:39 micro python[1112248]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Jun 16 23:14:39 micro python[1112248]: error: [Errno 32] Broken pipe

**Comment by chibbert** [comment]
My bad, the issue was with my prometheus config. I'm not sure why the exception occurred (this was at the same time I messed up my prometheus config file), but it wasn't the cause of my issue
